Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/donaldo9603/workspace/numeric/train_ae_model.py", line 109, in <module>
    main(args)
  File "/home/donaldo9603/workspace/numeric/train_ae_model.py", line 106, in main
    trainer.train()
  File "/home/donaldo9603/.conda/envs/numeric/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/donaldo9603/.conda/envs/numeric/lib/python3.11/site-packages/transformers/trainer.py", line 1569, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donaldo9603/.conda/envs/numeric/lib/python3.11/site-packages/transformers/trainer.py", line 837, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donaldo9603/.conda/envs/numeric/lib/python3.11/site-packages/transformers/trainer.py", line 808, in _get_train_sampler
    return RandomSampler(self.train_dataset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/donaldo9603/.conda/envs/numeric/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0